name: tester

on:
  push:
  workflow_dispatch:
jobs:
  test:
    strategy:    
      fail-fast: false
      matrix:
        os: [ubuntu-latest, self-hosted]
        usr: [root]
    name: runner / gotest
    runs-on: ${{ matrix.os }}
    container: 
      image: alvisisme/docker-ubuntu-non-root-with-utils:latest    
      options: --user ${{ matrix.usr }}
    steps:
      - run: whoami   
      - run: id
      # - run: sudo chown -R dev:dev /__w/_temp && echo “color=green” >> $GITHUB_ENV    
      - uses: actions/checkout@v3
  usrid:
    name: runneruserid
    runs-on: ubuntu-latest
    steps:
      - run: whoami   
      - run: id
