name: tester

on:
  push:
  workflow_dispatch:
jobs:
  test:
    strategy:    
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        usr: [root, dev]
    name: runner / gotest
    runs-on: ${{ matrix.os }}
    container: 
      image: alvisisme/docker-ubuntu-non-root-with-utils:latest    
      options: --user ${{ matrix.usr }}
    steps:
      - run: whoami   
      - run: id
      - run: sudo chown -R $USER:$USER /__w/_temp && echo $USER
      - run: echo “color=green” >> $GITHUB_ENV    
      - uses: actions/checkout@v3.1.0
  
