name: tester

on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: runner / gotest
    runs-on: self-hosted
    container: ghcr.io/runatlantis/testing-env:2021.08.31
    steps:
      - uses: actions/checkout@v3.1.0      
      - name: sleep post checkout
        run: sleep 10
