name: tester

on:
  push:
  workflow_dispatch:
jobs:
  strategy:
    matrix:
      os: [ubuntu-latest, self-hosted]
  test:
    name: runner / gotest
    runs-on: ${{ matrix.os }}
    container: ghcr.io/runatlantis/testing-env:2021.08.31
    steps:
      - uses: actions/checkout@v3.1.0
