name: tester

on:
  push:


jobs:
  test:
    name: runner / gotest
    runs-on: self-hosted
    container: ghcr.io/runatlantis/testing-env:2021.08.31
    steps:
      # user in image needs write access to do anything
      - name: setup
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp 
      - uses: actions/checkout@v3.1.0
