name: tester

on:
  push:
  workflow_dispatch:
jobs:
  test:
    strategy:    
      fail-fast: false
      matrix:
        os: [ubuntu-latest, self-hosted, ubi-vm]
        usr: [root, dev]
    name: runner / gotest
    runs-on: ${{ matrix.os }}
    container: 
      image: alvisisme/docker-ubuntu-non-root-with-utils:latest    
      options: --user ${{ matrix.usr }}
    steps:
      - run: whoami
      - run: echo ${{ github.workspace }}
      - run: echo $GITHUB_WORKSPACE      
      - run: sudo chown -R $USER:$USER /__w/_temp
      - run: echo “color=green” >> $GITHUB_ENV    
      - run: echo “color=green” >> $GITHUB_OUTPUT 
      - uses: actions/checkout@v3.1.0
  
