name: tester

on:
  push:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    name: runner / gotest
    runs-on: ${{ matrix.os }}
    container: 
      image: alvisisme/docker-ubuntu-non-root-with-utils:latest    
#      options: --user root
    steps:
      - run: whoami
      - run: echo ${{ github.workspace }}
      - run: echo $GITHUB_WORKSPACE      
      - run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v3.1.0
  
